includes:
  - configs/s2ef/all/base.yml

model:
  name: baseline
  otf_graph: true

optim:
  batch_size: 500
  eval_batch_size: 500
  num_workers: 8
  lr_initial: 0.00025
  lr_gamma: 0.3
  lr_milestones: # steps at which lr_initial <- lr_initial * lr_gamma
    - 150000
    - 200000
    - 300000
  warmup_steps: 100
  warmup_factor: 0.2
  optimizer: AdamW
  optimizer_params: {"amsgrad": True}
  eval_every: 5000
  max_epochs: 12
  clip_grad_norm: 20
  ema_decay: 0.999
