includes:
  - configs/s2ef/all/base.yml

dataset:
  train:
    format: lmdb
    src: /mnt/vast/home/theo/code/fairchem/src/fairchem/data/s2ef/all/train/
    key_mapping:
      y: energy
      force: forces
    transforms:
      normalizer:
        energy:
          mean: -0.7554450631141663
          stdev: 2.887317180633545
        forces:
          mean: 0
          stdev: 2.887317180633545
      
  val:
    src: /mnt/vast/home/theo/code/fairchem/src/fairchem/data/s2ef/all/val_id_small/
    # src: /mnt/vast/home/theo/code/fairchem/src/fairchem/data/s2ef/all/val_id/

model:
  name: debug
  otf_graph: true

optim:
  batch_size: 50
  eval_batch_size: 50
  load_balancing: atoms
  num_workers: 8
  lr_initial: 0.0002
  lr_gamma: 0.3
  lr_milestones: # steps at which lr_initial <- lr_initial * lr_gamma
    - 150000
    - 200000
    - 300000
  warmup_steps: 100
  warmup_factor: 0.2
  optimizer: AdamW
  optimizer_params: {"amsgrad": True}
  eval_every: 10000
  max_epochs: 12
  clip_grad_norm: 20
  ema_decay: 0.999
